name: binance_market
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 使用稳定版 k_chart
  k_chart: ^0.7.0
  dio: ^5.3.0
  web_socket_channel: ^2.4.0
  flutter_riverpod: ^2.4.0
  intl: ^0.18.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
